<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Yogeshwar-PC" failures="1" tests="2" name="Test(failed)" time="0.094" errors="0" timestamp="2022-07-14T16:27:32 IST">
  <testcase classname="TestNG.failed_Tesr" name="m5" time="0.017">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.failed_Tesr.m5(failed_Tesr.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- m5 -->
  <testcase classname="TestNG.failed_Tesr" name="m4" time="0.004"/>
  <testcase classname="TestNG.failed_Tesr" name="m1" time="0.0">
    <ignored/>
  </testcase> <!-- m1 -->
  <testcase classname="TestNG.failed_Tesr" name="m2" time="0.0">
    <ignored/>
  </testcase> <!-- m2 -->
  <testcase classname="TestNG.failed_Tesr" name="m3" time="0.0">
    <ignored/>
  </testcase> <!-- m3 -->
  <testcase classname="TestNG.failed_Tesr" name="m6" time="0.0">
    <ignored/>
  </testcase> <!-- m6 -->
</testsuite> <!-- Test(failed) -->
